/**
 * Jupyter Notebook Generator for AutoRA Workflows
 *
 * Produces the same Python program as the Python code generator, but split
 * into ordered notebook cells. The first code cell installs every package
 * required by the imports that follow.
 */

import {
  CodeBuilder,
  TEMPLATES,
  collectPipPackages,
  generateImports,
  generateVariablesSetup,
  generateWrapper,
  prepareWorkflow
} from './pythonGenerator'

/**
 * Build a notebook markdown cell from one or more lines of text.
 */
function markdownCell(text) {
  return {
    cell_type: 'markdown',
    metadata: {},
    source: toSource(text)
  }
}

/**
 * Build a notebook code cell from a block of source text.
 */
function codeCell(text) {
  return {
    cell_type: 'code',
    execution_count: null,
    metadata: {},
    outputs: [],
    source: toSource(text)
  }
}

/**
 * Convert a string into the array-of-lines form Jupyter uses for `source`,
 * where every line except the last keeps its trailing newline.
 */
function toSource(text) {
  const lines = text.split('\n')
  return lines.map((line, i) => (i < lines.length - 1 ? `${line}\n` : line))
}

/**
 * Build the "run the workflow" code cell. Unlike the standalone Python file,
 * the notebook runs the loop at top level so each cycle's state is inspectable.
 */
function buildRunCell(mainPath, loopPath, filterInfo, componentMeta) {
  const code = new CodeBuilder()

  // Variable setup + state initialization (templates are indented for a
  // function body, so strip the leading 4 spaces for top-level use).
  code.multiline(dedent(generateVariablesSetup(componentMeta, [...mainPath, ...loopPath])))
  code.blank()
  code.multiline(dedent(TEMPLATES.initState))
  code.blank()

  const maxCycles = filterInfo?.maxCounter ?? 10
  code.line(`# Main experiment loop (${maxCycles} cycles)`)
  code.line(`for i in range(${maxCycles}):`)
  code.indent("print(f'Cycle {i}')")
  code.blank()

  const addComponentCall = (node) => {
    const meta = componentMeta.get(node.id)
    if (!meta) return

    const { varName, nodeName, pythonName } = meta
    const isSampler = pythonName.includes('sample') || pythonName.includes('sampler')

    code.indent(`# ${nodeName}`)
    if (isSampler && node.parameters?.num_samples) {
      code.indent(`state = ${varName}(state, num_samples=${node.parameters.num_samples})`)
    } else {
      code.indent(`state = ${varName}(state)`)
    }
    code.blank()
  }

  mainPath.forEach(addComponentCall)
  loopPath.forEach(addComponentCall)

  code.blank()
  code.line('print("Workflow completed!")')
  code.line('state')

  return code.toString()
}

/**
 * Remove a single level (4 spaces) of leading indentation from each line so
 * function-body templates can be reused at notebook top level.
 */
function dedent(text) {
  return text
    .split('\n')
    .map(line => (line.startsWith('    ') ? line.slice(4) : line))
    .join('\n')
}

/**
 * Generate a Jupyter notebook (parsed JSON object) from workflow state.
 */
export function generateNotebook(state) {
  const { mainPath, loopPath, filterInfo, imports, componentMeta, hasRunner } = prepareWorkflow(state)

  const cells = []

  // 1. Title
  cells.push(markdownCell(
    `# AutoRA Workflow\n\n` +
    `Generated by AutoRA Workflow Editor on ${new Date().toISOString()}`
  ))

  // 2. Install dependencies (must cover every import that follows)
  cells.push(markdownCell('## 1. Install dependencies'))
  const pipPackages = collectPipPackages(state)
  const pipCell = pipPackages.length === 0
    ? '# No additional packages required'
    : `%pip install ${pipPackages.join(' ')}`
  cells.push(codeCell(pipCell))

  // 3. Imports
  cells.push(markdownCell('## 2. Imports'))
  const importsCode = new CodeBuilder()
  generateImports(importsCode, imports, { usesPlaceholderVariables: !hasRunner })
  cells.push(codeCell(importsCode.toString()))

  // 4. Component definitions (one code cell per component for clarity)
  cells.push(markdownCell('## 3. Component definitions'))
  componentMeta.forEach((meta) => {
    const wrapper = new CodeBuilder()
    generateWrapper(wrapper, meta)
    // Drop the trailing blank line each wrapper appends.
    cells.push(codeCell(wrapper.toString().replace(/\n+$/, '')))
  })

  // 5. Run the workflow
  cells.push(markdownCell('## 4. Run the workflow'))
  cells.push(codeCell(buildRunCell(mainPath, loopPath, filterInfo, componentMeta)))

  return {
    cells,
    metadata: {
      kernelspec: {
        display_name: 'Python 3',
        language: 'python',
        name: 'python3'
      },
      language_info: {
        name: 'python'
      }
    },
    nbformat: 4,
    nbformat_minor: 5
  }
}

/**
 * Generate the notebook as a formatted JSON string ready to write to a
 * `.ipynb` file.
 */
export function generateNotebookString(state) {
  return JSON.stringify(generateNotebook(state), null, 1)
}
