/**
 * Python Code Generator for AutoRA Workflows
 *
 * Generates executable Python code from workflow graph state.
 */

const CONTROL_NODE_TYPES = ['start_point', 'end_point', 'filter_point']

// Python code templates
const TEMPLATES = {
  header: (date) => `"""
AutoRA Workflow

Generated by AutoRA Workflow Editor
Generated on: ${date}
"""`,

  standardImports: `from dataclasses import dataclass, field
from typing import Optional, List

from autora.state import on_state, Delta, estimator_on_state, StandardState
from autora.variable import VariableCollection, Variable`,

  dataImports: `import pandas as pd
import numpy as np`,

  defaultVariables: `    # Initialize variables - customize this based on your experiment
    # You may need to define your own variables or get them from an experiment runner
    variables = VariableCollection(
        independent_variables=[
            Variable(name="x", allowed_values=np.linspace(-1, 1, 100))
        ],
        dependent_variables=[
            Variable(name="y")
        ]
    )`,

  initState: `    # Initialize state
    state = StandardState(variables=variables)`
}

/**
 * Simple code builder for cleaner Python generation
 */
class CodeBuilder {
  constructor() {
    this.lines = []
  }

  line(text = '') {
    this.lines.push(text)
    return this
  }

  indent(text, level = 1) {
    this.lines.push('    '.repeat(level) + text)
    return this
  }

  comment(text, level = 0) {
    return this.indent(`# ${text}`, level)
  }

  blank() {
    return this.line('')
  }

  multiline(text) {
    text.split('\n').forEach(l => this.line(l))
    return this
  }

  toString() {
    return this.lines.join('\n')
  }
}

/**
 * Traverse the workflow graph and return nodes in execution order
 */
function getExecutionOrder(nodes, connections) {
  const startNode = nodes.find(n => n.type === 'start_point')
  const endNode = nodes.find(n => n.type === 'end_point')
  const filterNodes = nodes.filter(n => n.type === 'filter_point')

  if (!startNode) {
    throw new Error('Workflow must have a Start node')
  }

  // Build adjacency map (source -> [targets])
  const adjacency = {}
  connections.forEach(conn => {
    if (!adjacency[conn.sourceId]) {
      adjacency[conn.sourceId] = []
    }
    adjacency[conn.sourceId].push(conn.targetId)
  })

  const mainPath = []
  const loopPath = []
  const visited = new Set()

  function findPath(fromId, toIds, path = []) {
    if (toIds.includes(fromId)) return [...path, fromId]
    if (visited.has(fromId)) return null
    visited.add(fromId)

    for (const targetId of (adjacency[fromId] || [])) {
      const result = findPath(targetId, toIds, [...path, fromId])
      if (result) return result
    }
    return null
  }

  const filterNode = filterNodes[0]

  if (filterNode) {
    visited.clear()
    const pathToFilter = findPath(startNode.id, [filterNode.id])
    const filterTargets = adjacency[filterNode.id] || []

    let loopBackTarget = null
    for (const targetId of filterTargets) {
      const targetNode = nodes.find(n => n.id === targetId)
      if (targetNode?.type !== 'end_point') {
        loopBackTarget = targetId
      }
    }

    if (pathToFilter) {
      for (let i = 1; i < pathToFilter.length; i++) {
        const node = nodes.find(n => n.id === pathToFilter[i])
        if (node && !CONTROL_NODE_TYPES.includes(node.type)) {
          mainPath.push(node)
        }
      }
    }

    if (loopBackTarget) {
      const loopNode = nodes.find(n => n.id === loopBackTarget)
      if (loopNode && !CONTROL_NODE_TYPES.includes(loopNode.type)) {
        if (!mainPath.find(n => n.id === loopBackTarget)) {
          loopPath.push(loopNode)
        }
      }
    }
  } else if (endNode) {
    visited.clear()
    const pathToEnd = findPath(startNode.id, [endNode.id])
    if (pathToEnd) {
      for (let i = 1; i < pathToEnd.length - 1; i++) {
        const node = nodes.find(n => n.id === pathToEnd[i])
        if (node && !CONTROL_NODE_TYPES.includes(node.type)) {
          mainPath.push(node)
        }
      }
    }
  }

  return {
    mainPath,
    loopPath,
    filterInfo: filterNode ? { maxCounter: filterNode.filterParams?.maxCounter ?? 10 } : null
  }
}

/**
 * Generate a valid Python variable name from a component name
 */
function toPythonName(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_')
}

/**
 * Format a JavaScript value as Python literal
 */
function formatPythonValue(value) {
  if (value === null || value === undefined) return 'None'
  if (typeof value === 'boolean') return value ? 'True' : 'False'
  if (typeof value === 'string') return `"${value.replace(/"/g, '\\"')}"`
  if (Array.isArray(value)) return `[${value.map(formatPythonValue).join(', ')}]`
  return String(value)
}

/**
 * Build parameter string from params object
 */
function buildParamString(params, exclude = []) {
  return Object.entries(params)
    .filter(([k, v]) => v !== null && v !== undefined && !exclude.includes(k))
    .map(([k, v]) => `${k}=${formatPythonValue(v)}`)
    .join(', ')
}

/**
 * Generate wrapper function for a theorist component
 */
function generateTheoristWrapper(code, meta) {
  const { pythonName, params, varName, nodeName } = meta
  const paramStr = buildParamString(params)

  code.comment(nodeName)
  code.line(`${varName} = estimator_on_state(${pythonName}(${paramStr}))`)
  code.blank()
}

/**
 * Generate wrapper function for an experiment runner component
 */
function generateRunnerWrapper(code, meta) {
  const { pythonName, params, varName, nodeName } = meta
  const paramStr = buildParamString(params)

  code.comment(nodeName)
  code.line('@on_state()')
  code.line(`def ${varName}(conditions: pd.DataFrame) -> Delta:`)
  code.indent(`runner = ${pythonName}(${paramStr})`)
  code.indent('assert runner.run is not None')
  code.indent('return Delta(experiment_data=runner.run(conditions=conditions))')
  code.blank()
}

/**
 * Generate wrapper function for an experimentalist component (pooler/sampler)
 */
function generateExperimentalistWrapper(code, meta) {
  const { pythonName, params, varName, nodeName } = meta
  const isPooler = pythonName.includes('pool')
  const isSampler = pythonName.includes('sample') || pythonName.includes('sampler')

  code.comment(nodeName)
  code.line('@on_state()')

  if (isPooler) {
    const paramStr = buildParamString(params)
    code.line(`def ${varName}(variables: VariableCollection) -> Delta:`)
    const call = paramStr
      ? `${pythonName}(variables, ${paramStr})`
      : `${pythonName}(variables)`
    code.indent(`return Delta(conditions=${call})`)
  } else if (isSampler) {
    const numSamples = params.num_samples || 1
    const otherParamStr = buildParamString(params, ['num_samples'])

    code.line(`def ${varName}(conditions: pd.DataFrame, num_samples: int = ${numSamples}) -> Delta:`)
    const call = otherParamStr
      ? `${pythonName}(conditions=conditions, num_samples=num_samples, ${otherParamStr})`
      : `${pythonName}(conditions=conditions, num_samples=num_samples)`
    code.indent(`return Delta(conditions=${call})`)
  } else {
    const paramStr = buildParamString(params)
    code.line(`def ${varName}(conditions: pd.DataFrame) -> Delta:`)
    const call = paramStr
      ? `${pythonName}(conditions, ${paramStr})`
      : `${pythonName}(conditions)`
    code.indent(`return Delta(conditions=${call})`)
  }
  code.blank()
}

/**
 * Generate Python code from workflow state
 */
export function generatePythonCode(state) {
  const { nodes, connections, components } = state
  const allComponents = components ? Object.values(components).flat() : []
  const { mainPath, loopPath, filterInfo } = getExecutionOrder(nodes, connections)

  if (mainPath.length === 0) {
    throw new Error('No components found in workflow. Add components and connect them.')
  }

  // Collect imports and component metadata
  const imports = new Map()
  const componentMeta = new Map()
  const allPathNodes = [...mainPath, ...loopPath]

  allPathNodes.forEach(node => {
    const protocol = allComponents.find(c => c.uuid === node.protocolUuid)
    if (!protocol) {
      console.warn(`Protocol not found for node: ${node.name}`)
      return
    }

    const { importPath, pythonName, protocolType } = protocol
    if (!imports.has(importPath)) imports.set(importPath, new Set())
    imports.get(importPath).add(pythonName)

    componentMeta.set(node.id, {
      importPath,
      pythonName,
      protocolType,
      params: node.parameters || {},
      varName: `${toPythonName(node.name)}_on_state`,
      nodeName: node.name
    })
  })

  // Build Python code
  const code = new CodeBuilder()

  // Header and imports
  code.multiline(TEMPLATES.header(new Date().toISOString()))
  code.blank()
  code.multiline(TEMPLATES.standardImports)

  imports.forEach((names, importPath) => {
    code.line(`from ${importPath} import ${Array.from(names).join(', ')}`)
  })

  code.blank()
  code.multiline(TEMPLATES.dataImports)
  code.blank().blank()

  // Generate wrapper functions
  componentMeta.forEach((meta) => {
    if (meta.protocolType === 'theorist') {
      generateTheoristWrapper(code, meta)
    } else if (meta.protocolType === 'experiment_runner') {
      generateRunnerWrapper(code, meta)
    } else {
      generateExperimentalistWrapper(code, meta)
    }
  })

  code.blank()

  // Generate main function
  code.line('def main():')
  code.multiline(TEMPLATES.defaultVariables)
  code.indent('')
  code.multiline(TEMPLATES.initState)
  code.indent('')

  const maxCycles = filterInfo?.maxCounter ?? 10
  code.indent(`# Main experiment loop (${maxCycles} cycles)`)
  code.indent(`for i in range(${maxCycles}):`)
  code.indent("print(f'Cycle {i}')", 2)
  code.indent('', 2)

  // Add component calls in execution order
  const addComponentCall = (node) => {
    const meta = componentMeta.get(node.id)
    if (!meta) return

    const { varName, nodeName, pythonName } = meta
    const isSampler = pythonName.includes('sample') || pythonName.includes('sampler')

    code.indent(`# ${nodeName}`, 2)
    if (isSampler && node.parameters?.num_samples) {
      code.indent(`state = ${varName}(state, num_samples=${node.parameters.num_samples})`, 2)
    } else {
      code.indent(`state = ${varName}(state)`, 2)
    }
    code.indent('', 2)
  }

  mainPath.forEach(addComponentCall)
  loopPath.forEach(addComponentCall)

  code.indent('')
  code.indent('print("Workflow completed!")')
  code.indent('return state')
  code.blank().blank()
  code.line("if __name__ == '__main__':")
  code.indent('main()')
  code.blank()

  return code.toString()
}

/**
 * Generate pip install commands for all required packages
 */
export function generatePipInstalls(state) {
  const { nodes, components } = state
  const allComponents = components ? Object.values(components).flat() : []
  const pipPackages = new Set()

  nodes.forEach(node => {
    if (CONTROL_NODE_TYPES.includes(node.type)) return
    const protocol = allComponents.find(c => c.uuid === node.protocolUuid)
    if (protocol?.pipInstall) pipPackages.add(protocol.pipInstall)
  })

  if (pipPackages.size === 0) return '# No additional packages required'
  return `pip install ${Array.from(pipPackages).join(' ')}`
}
