/**
 * Python Code Generator for AutoRA Workflows
 *
 * Generates executable Python code from workflow graph state.
 *
 * @module utils/pythonGenerator
 */

export const CONTROL_NODE_TYPES = ['start_point', 'end_point', 'filter_point']

// Python code templates
export const TEMPLATES = {
  header: (date) => `"""
AutoRA Workflow

Generated by AutoRA Workflow Editor
Generated on: ${date}
"""`,

  standardImports: `from autora.state import on_state, Delta, estimator_on_state, StandardState`,

  dataImports: `import pandas as pd`,

  defaultVariables: `    # Initialize variables - customize this based on your experiment
    # You may need to define your own variables or get them from an experiment runner
    variables = VariableCollection(
        independent_variables=[
            Variable(name="x", allowed_values=np.linspace(-1, 1, 100))
        ],
        dependent_variables=[
            Variable(name="y")
        ]
    )`,

  initState: `    # Initialize state
    state = StandardState(variables=variables)`
}

/**
 * Simple code builder for cleaner Python generation
 */
export class CodeBuilder {
  constructor() {
    this.lines = []
  }

  /**
   * Append a single line of text.
   *
   * @param {string} [text=''] - Line contents.
   * @returns {CodeBuilder} This builder, for chaining.
   */
  line(text = '') {
    this.lines.push(text)
    return this
  }

  /**
   * Append a line prefixed with the given number of 4-space indent levels.
   *
   * @param {string} text - Line contents.
   * @param {number} [level=1] - Number of indent levels.
   * @returns {CodeBuilder} This builder, for chaining.
   */
  indent(text, level = 1) {
    this.lines.push('    '.repeat(level) + text)
    return this
  }

  /**
   * Append a `#`-prefixed Python comment at the given indent level.
   *
   * @param {string} text - Comment text (without the leading `#`).
   * @param {number} [level=0] - Number of indent levels.
   * @returns {CodeBuilder} This builder, for chaining.
   */
  comment(text, level = 0) {
    return this.indent(`# ${text}`, level)
  }

  /**
   * Append a blank line.
   *
   * @returns {CodeBuilder} This builder, for chaining.
   */
  blank() {
    return this.line('')
  }

  /**
   * Append a multi-line string as separate lines.
   *
   * @param {string} text - Newline-separated text.
   * @returns {CodeBuilder} This builder, for chaining.
   */
  multiline(text) {
    text.split('\n').forEach(l => this.line(l))
    return this
  }

  /**
   * Render all accumulated lines as a single newline-joined string.
   *
   * @returns {string} The built source code.
   */
  toString() {
    return this.lines.join('\n')
  }
}

/**
 * Traverse the workflow graph and return nodes in execution order
 *
 * @param {Object[]} nodes - Graph nodes, each with `id`, `type` and optional `filterParams`.
 * @param {Object[]} connections - Graph edges, each with `sourceId` and `targetId`.
 * @returns {Object} `{ mainPath, loopPath, filterInfo }` where the paths are ordered node arrays and `filterInfo` is `{ maxCounter }` or null.
 */
export function getExecutionOrder(nodes, connections) {
  const startNode = nodes.find(n => n.type === 'start_point')
  const endNode = nodes.find(n => n.type === 'end_point')
  const filterNodes = nodes.filter(n => n.type === 'filter_point')

  if (!startNode) {
    throw new Error('Workflow must have a Start node')
  }

  // Build adjacency map (source -> [targets])
  const adjacency = {}
  connections.forEach(conn => {
    if (!adjacency[conn.sourceId]) {
      adjacency[conn.sourceId] = []
    }
    adjacency[conn.sourceId].push(conn.targetId)
  })

  const mainPath = []
  const loopPath = []
  const visited = new Set()

  /**
   * Depth-first search for a path of node ids from a start node to any target.
   *
   * @param {string} fromId - Node id to start from.
   * @param {string[]} toIds - Target node ids to search for.
   * @param {string[]} [path=[]] - Accumulated ids on the current path.
   * @returns {string[]|null} Ordered node ids from start to target (inclusive), or null if none.
   */
  function findPath(fromId, toIds, path = []) {
    if (toIds.includes(fromId)) return [...path, fromId]
    if (visited.has(fromId)) return null
    visited.add(fromId)

    for (const targetId of (adjacency[fromId] || [])) {
      const result = findPath(targetId, toIds, [...path, fromId])
      if (result) return result
    }
    return null
  }

  const filterNode = filterNodes[0]

  if (filterNode) {
    visited.clear()
    const pathToFilter = findPath(startNode.id, [filterNode.id])
    const filterTargets = adjacency[filterNode.id] || []

    let loopBackTarget = null
    for (const targetId of filterTargets) {
      const targetNode = nodes.find(n => n.id === targetId)
      if (targetNode?.type !== 'end_point') {
        loopBackTarget = targetId
      }
    }

    // A Filter must have a second (loop-back) output connection to close the
    // experiment loop. Without it there is no cycle, so refuse to generate code
    // that would emit a misleading `for i in range(...)` loop.
    if (!loopBackTarget) {
      throw new Error(
        'The Filter node is missing its second output connection that closes the ' +
        'experiment loop. Please connect the Filter back to a component to form the ' +
        'loop before generating code.'
      )
    }

    if (pathToFilter) {
      for (let i = 1; i < pathToFilter.length; i++) {
        const node = nodes.find(n => n.id === pathToFilter[i])
        if (node && !CONTROL_NODE_TYPES.includes(node.type)) {
          mainPath.push(node)
        }
      }
    }

    if (loopBackTarget) {
      const loopNode = nodes.find(n => n.id === loopBackTarget)
      if (loopNode && !CONTROL_NODE_TYPES.includes(loopNode.type)) {
        if (!mainPath.find(n => n.id === loopBackTarget)) {
          loopPath.push(loopNode)
        }
      }
    }
  } else if (endNode) {
    visited.clear()
    const pathToEnd = findPath(startNode.id, [endNode.id])
    if (pathToEnd) {
      for (let i = 1; i < pathToEnd.length - 1; i++) {
        const node = nodes.find(n => n.id === pathToEnd[i])
        if (node && !CONTROL_NODE_TYPES.includes(node.type)) {
          mainPath.push(node)
        }
      }
    }
  }

  return {
    mainPath,
    loopPath,
    filterInfo: filterNode ? { maxCounter: filterNode.filterParams?.maxCounter ?? 10 } : null
  }
}

/**
 * Generate a valid Python variable name from a component name.
 * Parenthesized qualifiers like "(Synthetic, Economics)" are dropped.
 *
 * @param {string} name - Human-readable component name.
 * @returns {string} A lowercase, underscore-separated identifier.
 */
export function toPythonName(name) {
  return name
    .replace(/\([^)]*\)/g, ' ')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_')
}

/**
 * Format a JavaScript value as Python literal
 *
 * @param {*} value - Value to format (null/undefined, boolean, string, array or number).
 * @returns {string} The Python literal representation.
 */
function formatPythonValue(value) {
  if (value === null || value === undefined) return 'None'
  if (typeof value === 'boolean') return value ? 'True' : 'False'
  if (typeof value === 'string') {
    // A string that already holds a Python container literal (dict or list),
    // e.g. a "dict"-typed field like fixed_effects, is emitted verbatim so it
    // is not wrapped in quotes and stays a real dict/list in the generated code.
    const trimmed = value.trim()
    if (/^\{[\s\S]*\}$/.test(trimmed) || /^\[[\s\S]*\]$/.test(trimmed)) return trimmed
    return `"${value.replace(/"/g, '\\"')}"`
  }
  if (Array.isArray(value)) return `[${value.map(formatPythonValue).join(', ')}]`
  return String(value)
}

/**
 * Build parameter string from params object
 *
 * @param {Object} params - Map of parameter name to value.
 * @param {string[]} [exclude=[]] - Parameter names to omit.
 * @returns {string} Comma-separated `name=value` keyword arguments (nulls skipped).
 */
function buildParamString(params, exclude = []) {
  return Object.entries(params)
    .filter(([k, v]) => v !== null && v !== undefined && !exclude.includes(k))
    .map(([k, v]) => `${k}=${formatPythonValue(v)}`)
    .join(', ')
}

/**
 * Generate wrapper function for a theorist component
 *
 * @param {CodeBuilder} code - Builder to append the wrapper to.
 * @param {Object} meta - Component metadata with `pythonName`, `params`, `varName`, `nodeName` and `runParamNames` (non-constructor params to exclude from instantiation).
 * @returns {void}
 */
function generateTheoristWrapper(code, meta) {
  const { pythonName, params, varName, nodeName, runParamNames = [] } = meta
  // Only pass constructor (__init__) params to instantiation; params belonging
  // to other methods (e.g. fit) are excluded so instantiation does not fail.
  const paramStr = buildParamString(params, runParamNames)

  code.comment(nodeName)
  code.line(`${varName} = estimator_on_state(${pythonName}(${paramStr}))`)
  code.blank()
}

/**
 * Generate wrapper function for an experiment runner component
 *
 * @param {CodeBuilder} code - Builder to append the wrapper to.
 * @param {Object} meta - Component metadata with `pythonName`, `params`, `varName`, `nodeName` and `runParamNames`.
 * @returns {void}
 */
function generateRunnerWrapper(code, meta) {
  const { pythonName, params, varName, nodeName, runParamNames = [] } = meta
  const factoryParamStr = buildParamString(params, runParamNames)
  const runParamStr = buildParamString(
    Object.fromEntries(Object.entries(params).filter(([name]) => runParamNames.includes(name)))
  )
  const runArgs = ['conditions=conditions', runParamStr].filter(Boolean).join(', ')

  code.comment(nodeName)
  code.line('@on_state()')
  code.line(`def ${varName}(conditions: pd.DataFrame) -> Delta:`)
  code.indent(`runner = ${pythonName}(${factoryParamStr})`)
  code.indent('assert runner.run is not None')
  code.indent(`return Delta(experiment_data=runner.run(${runArgs}))`)
  code.blank()
}

/**
 * Find the variable name of a data type spec, descending through list wrappers
 *
 * @param {Object} dataType - Data type spec with a `name` or a nested `variable`.
 * @returns {string|null} The resolved data type name, or null if none.
 */
function dataTypeName(dataType) {
  if (!dataType) return null
  if (dataType.name) return dataType.name
  if (dataType.variable) return dataTypeName(dataType.variable)
  return null
}

/**
 * Generate wrapper function for an experimentalist component (pooler/sampler)
 *
 * @param {CodeBuilder} code - Builder to append the wrapper to.
 * @param {Object} meta - Component metadata with `pythonName`, `params`, `varName`, `nodeName`, `inputDataType` and `outputDataType`.
 * @returns {void}
 */
function generateExperimentalistWrapper(code, meta) {
  const { pythonName, params, varName, nodeName, inputDataType, outputDataType } = meta
  const isPooler = pythonName.includes('pool')
  const isSampler = pythonName.includes('sample') || pythonName.includes('sampler')

  code.comment(nodeName)
  code.line('@on_state()')

  if (inputDataType === null) {
    // Component consumes nothing from state (e.g. bandit random pooler):
    // all of its inputs are plain parameters. Its raw output (nested lists)
    // is wrapped in a DataFrame column so StandardState can coerce it.
    const paramStr = buildParamString(params)
    const call = `${pythonName}(${paramStr})`
    const outName = dataTypeName(outputDataType)
    const value = outName ? `pd.DataFrame({"${outName}": ${call}})` : call
    code.line(`def ${varName}() -> Delta:`)
    code.indent(`return Delta(conditions=${value})`)
  } else if (isPooler) {
    const paramStr = buildParamString(params)
    code.line(`def ${varName}(variables: VariableCollection) -> Delta:`)
    const call = paramStr
      ? `${pythonName}(variables, ${paramStr})`
      : `${pythonName}(variables)`
    code.indent(`return Delta(conditions=${call})`)
  } else if (isSampler) {
    const numSamples = params.num_samples || 1
    const otherParamStr = buildParamString(params, ['num_samples'])

    code.line(`def ${varName}(conditions: pd.DataFrame, num_samples: int = ${numSamples}) -> Delta:`)
    const call = otherParamStr
      ? `${pythonName}(conditions=conditions, num_samples=num_samples, ${otherParamStr})`
      : `${pythonName}(conditions=conditions, num_samples=num_samples)`
    code.indent(`return Delta(conditions=${call})`)
  } else {
    const paramStr = buildParamString(params)
    code.line(`def ${varName}(conditions: pd.DataFrame) -> Delta:`)
    const call = paramStr
      ? `${pythonName}(conditions, ${paramStr})`
      : `${pythonName}(conditions)`
    code.indent(`return Delta(conditions=${call})`)
  }
  code.blank()
}

/**
 * Dispatch wrapper generation based on the component's protocol type.
 *
 * @param {CodeBuilder} code - Builder to append the wrapper to.
 * @param {Object} meta - Component metadata; `protocolType` selects the wrapper style.
 * @returns {void}
 */
export function generateWrapper(code, meta) {
  if (meta.protocolType === 'theorist') {
    generateTheoristWrapper(code, meta)
  } else if (meta.protocolType === 'experiment_runner') {
    generateRunnerWrapper(code, meta)
  } else {
    generateExperimentalistWrapper(code, meta)
  }
}

/**
 * Collect execution order, imports and per-component metadata from the
 * workflow state. Shared by the Python file and Jupyter notebook generators.
 *
 * @param {Object} state - Editor state with `nodes`, `connections` and `components`.
 * @returns {Object} `{ mainPath, loopPath, filterInfo, imports, componentMeta, hasRunner }`.
 */
export function prepareWorkflow(state) {
  const { nodes, connections, components } = state
  const allComponents = components ? Object.values(components).flat() : []
  const { mainPath, loopPath, filterInfo } = getExecutionOrder(nodes, connections)

  if (mainPath.length === 0) {
    throw new Error('No components found in workflow. Add components and connect them.')
  }

  // Collect imports and component metadata
  const imports = new Map()
  const componentMeta = new Map()
  const allPathNodes = [...mainPath, ...loopPath]

  allPathNodes.forEach(node => {
    const protocol = allComponents.find(c => c.uuid === node.protocolUuid)
    if (!protocol) {
      console.warn(`Protocol not found for node: ${node.name}`)
      return
    }

    const { importPath, pythonName, protocolType, file, inputDataType } = protocol

    // Experimentalist pythonNames are bare function names (pool, sample, ...)
    // shared across modules, so import them aliased to the JSON file name
    let alias = null
    if (protocolType === 'experimentalist' && file) {
      const fileAlias = toPythonName(file.replace(/\.json$/, ''))
      if (fileAlias && fileAlias !== pythonName) alias = fileAlias
    }

    if (!imports.has(importPath)) imports.set(importPath, new Set())
    imports.get(importPath).add(alias ? `${pythonName} as ${alias}` : pythonName)

    // Parameters are grouped by function in the JSON. The instantiation group
    // configures the constructor/factory: theorist classes use an "__init__"
    // group, runner factories use a group named after the function (pythonName).
    // Any other group (e.g. "fit" for a theorist, "run" for a runner) is applied
    // elsewhere, not at instantiation, so its params must be excluded from it.
    const initGroup = protocol.parameters?.[pythonName] || protocol.parameters?.['__init__'] || []
    const factoryParamNames = new Set(initGroup.map(p => p.name))
    const runParamNames = Object.values(protocol.parameters || {})
      .flatMap(groupParams => (Array.isArray(groupParams) ? groupParams : []).map(p => p.name))
      .filter(name => !factoryParamNames.has(name))

    componentMeta.set(node.id, {
      importPath,
      // Name as imported into the generated file (alias when aliased)
      pythonName: alias || pythonName,
      inputDataType,
      outputDataType: protocol.outputDataType,
      runParamNames,
      protocolType,
      params: node.parameters || {},
      varName: `${toPythonName(node.name)}_on_state`,
      nodeName: node.name
    })
  })

  const hasRunner = [...componentMeta.values()]
    .some(meta => meta.protocolType === 'experiment_runner')

  return { mainPath, loopPath, filterInfo, imports, componentMeta, hasRunner }
}

/**
 * Build the variables-initialization block (indented for a function body).
 * When the workflow contains an experiment runner, the variables are created
 * and governed by the runner; otherwise fall back to the placeholder template.
 *
 * @param {Map} componentMeta - Map of node id to component metadata.
 * @param {Object[]} orderedNodes - Nodes in execution order, used to find any runner.
 * @returns {string} Indented Python source for the variables setup block.
 */
export function generateVariablesSetup(componentMeta, orderedNodes) {
  const runnerMeta = orderedNodes
    .map(node => componentMeta.get(node.id))
    .find(meta => meta?.protocolType === 'experiment_runner')

  if (!runnerMeta) return TEMPLATES.defaultVariables

  const paramStr = buildParamString(runnerMeta.params, runnerMeta.runParamNames || [])
  return [
    '    # Variables are created and governed by the experiment runner',
    `    runner = ${runnerMeta.pythonName}(${paramStr})`,
    '    assert runner.variables is not None',
    '    variables = runner.variables'
  ].join('\n')
}

/**
 * Emit the import block (standard + component + data imports) into a builder.
 * `Variable` and numpy are only needed by the placeholder variables template,
 * so they are skipped when the variables come from an experiment runner.
 *
 * @param {CodeBuilder} code - Builder to append the imports to.
 * @param {Map} imports - Map of import path to a Set of imported (possibly aliased) names.
 * @param {Object} [options] - Options object.
 * @param {boolean} [options.usesPlaceholderVariables=true] - Whether to also import `Variable` and numpy for the placeholder template.
 * @returns {void}
 */
export function generateImports(code, imports, { usesPlaceholderVariables = true } = {}) {
  code.multiline(TEMPLATES.standardImports)
  code.line(`from autora.variable import VariableCollection${usesPlaceholderVariables ? ', Variable' : ''}`)

  imports.forEach((names, importPath) => {
    code.line(`from ${importPath} import ${Array.from(names).join(', ')}`)
  })

  code.blank()
  code.multiline(TEMPLATES.dataImports)
  if (usesPlaceholderVariables) code.line('import numpy as np')
}

/**
 * Generate Python code from workflow state
 *
 * @param {Object} state - Editor state with `nodes`, `connections` and `components`.
 * @returns {string} A complete, runnable Python script as a string.
 */
export function generatePythonCode(state) {
  const { mainPath, loopPath, filterInfo, imports, componentMeta, hasRunner } = prepareWorkflow(state)

  // Build Python code
  const code = new CodeBuilder()

  // Header and imports
  code.multiline(TEMPLATES.header(new Date().toISOString()))
  code.blank()
  generateImports(code, imports, { usesPlaceholderVariables: !hasRunner })
  code.blank().blank()

  // Generate wrapper functions
  componentMeta.forEach((meta) => generateWrapper(code, meta))

  code.blank()

  // Generate main function
  code.line('def main():')
  code.multiline(generateVariablesSetup(componentMeta, [...mainPath, ...loopPath]))
  code.indent('')
  code.multiline(TEMPLATES.initState)
  code.indent('')

  const maxCycles = filterInfo?.maxCounter ?? 10
  code.indent(`# Main experiment loop (${maxCycles} cycles)`)
  code.indent(`for i in range(${maxCycles}):`)
  code.indent("print(f'Cycle {i}')", 2)
  code.indent('', 2)

  // Add component calls in execution order
  const addComponentCall = (node) => {
    const meta = componentMeta.get(node.id)
    if (!meta) return

    const { varName, nodeName, pythonName } = meta
    const isSampler = pythonName.includes('sample') || pythonName.includes('sampler')

    code.indent(`# ${nodeName}`, 2)
    if (isSampler && node.parameters?.num_samples) {
      code.indent(`state = ${varName}(state, num_samples=${node.parameters.num_samples})`, 2)
    } else {
      code.indent(`state = ${varName}(state)`, 2)
    }
    code.indent('', 2)
  }

  mainPath.forEach(addComponentCall)
  loopPath.forEach(addComponentCall)

  code.indent('')
  code.indent('print("Workflow completed!")')
  code.indent('return state')
  code.blank().blank()
  code.line("if __name__ == '__main__':")
  code.indent('main()')
  code.blank()

  return code.toString()
}

/**
 * Collect the set of pip packages required by the workflow's components.
 *
 * @param {Object} state - Editor state with `nodes` and `components`.
 * @returns {string[]} Deduplicated list of pip package specifiers.
 */
export function collectPipPackages(state) {
  const { nodes, components } = state
  const allComponents = components ? Object.values(components).flat() : []
  const pipPackages = new Set()

  nodes.forEach(node => {
    if (CONTROL_NODE_TYPES.includes(node.type)) return
    const protocol = allComponents.find(c => c.uuid === node.protocolUuid)
    if (protocol?.pipInstall) pipPackages.add(protocol.pipInstall)
  })

  return Array.from(pipPackages)
}

/**
 * Generate pip install commands for all required packages
 *
 * @param {Object} state - Editor state with `nodes` and `components`.
 * @returns {string} A `pip install ...` command, or a comment when none are required.
 */
export function generatePipInstalls(state) {
  const pipPackages = collectPipPackages(state)

  if (pipPackages.length === 0) return '# No additional packages required'
  return `pip install ${pipPackages.join(' ')}`
}
