"""Tests for build_standalone.py"""

import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from autora_gui.react_app.build_standalone import (
    create_single_html,
    generate_components_js,
    load_components,
    run_npm_build,
)


def test_load_components_returns_dict():
    """Test that load_components returns a dictionary."""
    components = load_components()
    assert isinstance(components, dict)


def test_load_components_has_expected_categories():
    """Test that load_components returns expected component categories."""
    components = load_components()
    expected = {"theorists", "experimentalists", "experiment_runners"}
    assert expected.issubset(set(components.keys()))


def test_load_components_items_have_required_fields():
    """Test that loaded components have required fields."""
    components = load_components()
    required_fields = {"uuid", "name", "protocolType"}

    for category, items in components.items():
        for item in items:
            for field in required_fields:
                assert field in item, f"Missing {field} in {category}/{item.get('name', 'unknown')}"


def test_generate_components_js_creates_valid_js():
    """Test that generate_components_js creates valid JavaScript."""
    test_components = {
        "theorists": [{"uuid": "test-1", "name": "Test Theorist"}],
        "experimentalists": [],
    }
    js_code = generate_components_js(test_components)

    assert "export const EMBEDDED_COMPONENTS" in js_code
    assert "Auto-generated by build_standalone.py" in js_code
    assert "1 components from 2 categories" in js_code


def test_generate_components_js_contains_component_data():
    """Test that generated JS contains the component data."""
    test_components = {
        "category1": [{"uuid": "abc-123", "name": "Test Component"}],
    }
    js_code = generate_components_js(test_components)

    assert "abc-123" in js_code
    assert "Test Component" in js_code


def test_generate_components_js_empty_input():
    """Test generate_components_js with empty input."""
    js_code = generate_components_js({})

    assert "export const EMBEDDED_COMPONENTS" in js_code
    assert "0 components from 0 categories" in js_code


def test_generate_components_js_multiple_categories():
    """Test generate_components_js with multiple categories."""
    test_components = {
        "theorists": [{"uuid": "t1"}, {"uuid": "t2"}],
        "experimentalists": [{"uuid": "e1"}],
        "experiment_runners": [{"uuid": "r1"}, {"uuid": "r2"}, {"uuid": "r3"}],
    }
    js_code = generate_components_js(test_components)

    assert "6 components from 3 categories" in js_code


def test_generate_components_js_special_characters():
    """Test that special characters are properly escaped in JSON."""
    test_components = {
        "category": [{"name": 'Test "quoted" & <special>'}],
    }
    js_code = generate_components_js(test_components)

    # JSON should escape quotes
    assert '\\"quoted\\"' in js_code or '"quoted"' in js_code


def test_load_components_adds_file_field():
    """Test that load_components adds the 'file' field to each component."""
    components = load_components()

    for category, items in components.items():
        for item in items:
            assert "file" in item, f"Missing 'file' field in {category}/{item.get('name', 'unknown')}"
            assert item["file"].endswith(".json")


def test_load_components_sorts_files():
    """Test that components within each category are loaded in sorted order."""
    components = load_components()

    for category, items in components.items():
        if len(items) > 1:
            file_names = [item["file"] for item in items]
            assert file_names == sorted(file_names), f"Components in {category} are not sorted"


class TestCreateSingleHtml:
    """Tests for create_single_html function."""

    def test_returns_false_if_index_not_found(self):
        """Test that create_single_html returns False if index.html doesn't exist."""
        with tempfile.TemporaryDirectory() as tmpdir:
            dist_dir = Path(tmpdir) / "dist"
            dist_dir.mkdir()
            output_file = Path(tmpdir) / "output.html"

            result = create_single_html(dist_dir, output_file)

            assert result is False
            assert not output_file.exists()

    def test_inlines_css_with_crossorigin(self):
        """Test that CSS files are inlined correctly with crossorigin attribute."""
        with tempfile.TemporaryDirectory() as tmpdir:
            dist_dir = Path(tmpdir) / "dist"
            assets_dir = dist_dir / "assets"
            assets_dir.mkdir(parents=True)

            # Create index.html with CSS link
            index_html = dist_dir / "index.html"
            index_html.write_text(
                '<html><head><link rel="stylesheet" crossorigin href="./assets/style.css"></head></html>'
            )

            # Create CSS file
            css_file = assets_dir / "style.css"
            css_file.write_text("body { color: red; }")

            output_file = Path(tmpdir) / "output.html"
            result = create_single_html(dist_dir, output_file)

            assert result is True
            content = output_file.read_text()
            assert "<style>body { color: red; }</style>" in content
            assert "href=" not in content

    def test_inlines_css_without_crossorigin(self):
        """Test that CSS files are inlined correctly without crossorigin attribute."""
        with tempfile.TemporaryDirectory() as tmpdir:
            dist_dir = Path(tmpdir) / "dist"
            assets_dir = dist_dir / "assets"
            assets_dir.mkdir(parents=True)

            index_html = dist_dir / "index.html"
            index_html.write_text('<html><head><link rel="stylesheet" href="./assets/style.css"></head></html>')

            css_file = assets_dir / "style.css"
            css_file.write_text(".test { margin: 0; }")

            output_file = Path(tmpdir) / "output.html"
            result = create_single_html(dist_dir, output_file)

            assert result is True
            content = output_file.read_text()
            assert "<style>.test { margin: 0; }</style>" in content

    def test_inlines_js_with_crossorigin(self):
        """Test that JS files are inlined correctly with crossorigin attribute."""
        with tempfile.TemporaryDirectory() as tmpdir:
            dist_dir = Path(tmpdir) / "dist"
            assets_dir = dist_dir / "assets"
            assets_dir.mkdir(parents=True)

            index_html = dist_dir / "index.html"
            index_html.write_text(
                '<html><body><script type="module" crossorigin src="./assets/main.js"></script></body></html>'
            )

            js_file = assets_dir / "main.js"
            js_file.write_text('console.log("hello");')

            output_file = Path(tmpdir) / "output.html"
            result = create_single_html(dist_dir, output_file)

            assert result is True
            content = output_file.read_text()
            assert '<script type="module">console.log("hello");</script>' in content
            assert "src=" not in content

    def test_inlines_js_without_crossorigin(self):
        """Test that JS files are inlined correctly without crossorigin attribute."""
        with tempfile.TemporaryDirectory() as tmpdir:
            dist_dir = Path(tmpdir) / "dist"
            assets_dir = dist_dir / "assets"
            assets_dir.mkdir(parents=True)

            index_html = dist_dir / "index.html"
            index_html.write_text('<html><body><script type="module" src="./assets/app.js"></script></body></html>')

            js_file = assets_dir / "app.js"
            js_file.write_text("const x = 1;")

            output_file = Path(tmpdir) / "output.html"
            result = create_single_html(dist_dir, output_file)

            assert result is True
            content = output_file.read_text()
            assert '<script type="module">const x = 1;</script>' in content

    def test_inlines_multiple_assets(self):
        """Test that multiple CSS and JS files are all inlined."""
        with tempfile.TemporaryDirectory() as tmpdir:
            dist_dir = Path(tmpdir) / "dist"
            assets_dir = dist_dir / "assets"
            assets_dir.mkdir(parents=True)

            index_html = dist_dir / "index.html"
            index_html.write_text(
                "<html>"
                '<head><link rel="stylesheet" crossorigin href="./assets/a.css">'
                '<link rel="stylesheet" crossorigin href="./assets/b.css"></head>'
                '<body><script type="module" crossorigin src="./assets/x.js"></script>'
                '<script type="module" crossorigin src="./assets/y.js"></script></body>'
                "</html>"
            )

            (assets_dir / "a.css").write_text(".a {}")
            (assets_dir / "b.css").write_text(".b {}")
            (assets_dir / "x.js").write_text("let x;")
            (assets_dir / "y.js").write_text("let y;")

            output_file = Path(tmpdir) / "output.html"
            result = create_single_html(dist_dir, output_file)

            assert result is True
            content = output_file.read_text()
            assert "<style>.a {}</style>" in content
            assert "<style>.b {}</style>" in content
            assert '<script type="module">let x;</script>' in content
            assert '<script type="module">let y;</script>' in content


class TestRunNpmBuild:
    """Tests for run_npm_build function."""

    @patch("autora_gui.react_app.build_standalone.subprocess.run")
    def test_returns_true_on_success(self, mock_run):
        """Test that run_npm_build returns True when both commands succeed."""
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")

        result = run_npm_build(Path("/fake/path"))

        assert result is True
        assert mock_run.call_count == 2

    @patch("autora_gui.react_app.build_standalone.subprocess.run")
    def test_returns_false_when_npm_install_fails(self, mock_run):
        """Test that run_npm_build returns False when npm install fails."""
        mock_run.return_value = MagicMock(returncode=1, stdout="", stderr="npm install error")

        result = run_npm_build(Path("/fake/path"))

        assert result is False
        assert mock_run.call_count == 1  # Should stop after first failure

    @patch("autora_gui.react_app.build_standalone.subprocess.run")
    def test_returns_false_when_npm_build_fails(self, mock_run):
        """Test that run_npm_build returns False when npm build fails."""
        # First call (npm install) succeeds, second call (npm build) fails
        mock_run.side_effect = [
            MagicMock(returncode=0, stdout="", stderr=""),
            MagicMock(returncode=1, stdout="build output", stderr="build error"),
        ]

        result = run_npm_build(Path("/fake/path"))

        assert result is False
        assert mock_run.call_count == 2

    @patch("autora_gui.react_app.build_standalone.subprocess.run")
    def test_calls_npm_install_first(self, mock_run):
        """Test that npm install is called before npm build."""
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")
        test_path = Path("/test/react/app")

        run_npm_build(test_path)

        calls = mock_run.call_args_list
        assert calls[0][0][0] == ["npm", "install"]
        assert calls[0][1]["cwd"] == test_path

    @patch("autora_gui.react_app.build_standalone.subprocess.run")
    def test_calls_npm_run_build_second(self, mock_run):
        """Test that npm run build is called after npm install."""
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")
        test_path = Path("/test/react/app")

        run_npm_build(test_path)

        calls = mock_run.call_args_list
        assert calls[1][0][0] == ["npm", "run", "build"]
        assert calls[1][1]["cwd"] == test_path

    @patch("autora_gui.react_app.build_standalone.subprocess.run")
    def test_captures_output(self, mock_run):
        """Test that subprocess output is captured."""
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")

        run_npm_build(Path("/fake/path"))

        for call in mock_run.call_args_list:
            assert call[1]["capture_output"] is True
            assert call[1]["text"] is True


class TestMain:
    """Tests for main function."""

    def test_main_exits_on_build_failure(self):
        """Test that main exits with code 1 when build fails."""
        from autora_gui.react_app.build_standalone import main

        with (
            patch(
                "autora_gui.react_app.build_standalone.load_components",
                return_value={"theorists": []},
            ),
            patch("autora_gui.react_app.build_standalone.run_npm_build", return_value=False),
            tempfile.TemporaryDirectory() as tmpdir,
            patch("autora_gui.react_app.build_standalone.Path") as mock_path,
        ):
            mock_react_dir = Path(tmpdir)
            mock_path.return_value.parent = mock_react_dir

            # Create required directories
            data_dir = mock_react_dir / "src" / "data"
            data_dir.mkdir(parents=True, exist_ok=True)

            with pytest.raises(SystemExit) as exc_info:
                main()

            assert exc_info.value.code == 1

    def test_main_calls_all_build_steps(self):
        """Test that main calls load_components, generate_components_js, and run_npm_build."""
        from autora_gui.react_app.build_standalone import main

        with (
            patch(
                "autora_gui.react_app.build_standalone.load_components",
                return_value={"theorists": []},
            ) as mock_load,
            patch("autora_gui.react_app.build_standalone.run_npm_build", return_value=True) as mock_npm,
            patch(
                "autora_gui.react_app.build_standalone.create_single_html",
                return_value=True,
            ) as mock_html,
            tempfile.TemporaryDirectory() as tmpdir,
            patch("autora_gui.react_app.build_standalone.Path") as mock_path,
        ):
            mock_react_dir = Path(tmpdir)
            mock_path.return_value.parent = mock_react_dir

            # Create required directories and files
            data_dir = mock_react_dir / "src" / "data"
            data_dir.mkdir(parents=True, exist_ok=True)

            # Create mock output file for stat()
            root_dir = mock_react_dir.parent.parent
            root_dir.mkdir(parents=True, exist_ok=True)
            output_file = root_dir / "index.html"
            output_file.write_text("<html></html>")

            main()

            mock_load.assert_called_once()
            mock_npm.assert_called_once()
            mock_html.assert_called_once()
