"""Tests for build_standalone.py"""

from autora_gui.react_app.build_standalone import (
    generate_components_js,
    load_components,
)


def test_load_components_returns_dict():
    """Test that load_components returns a dictionary."""
    components = load_components()
    assert isinstance(components, dict)


def test_load_components_has_expected_categories():
    """Test that load_components returns expected component categories."""
    components = load_components()
    expected = {"theorists", "experimentalists", "experiment_runners"}
    assert expected.issubset(set(components.keys()))


def test_load_components_items_have_required_fields():
    """Test that loaded components have required fields."""
    components = load_components()
    required_fields = {"uuid", "name", "protocolType"}

    for category, items in components.items():
        for item in items:
            for field in required_fields:
                assert field in item, f"Missing {field} in {category}/{item.get('name', 'unknown')}"


def test_generate_components_js_creates_valid_js():
    """Test that generate_components_js creates valid JavaScript."""
    test_components = {
        "theorists": [{"uuid": "test-1", "name": "Test Theorist"}],
        "experimentalists": [],
    }
    js_code = generate_components_js(test_components)

    assert "export const EMBEDDED_COMPONENTS" in js_code
    assert "Auto-generated by build_standalone.py" in js_code
    assert "1 components from 2 categories" in js_code


def test_generate_components_js_contains_component_data():
    """Test that generated JS contains the component data."""
    test_components = {
        "category1": [{"uuid": "abc-123", "name": "Test Component"}],
    }
    js_code = generate_components_js(test_components)

    assert "abc-123" in js_code
    assert "Test Component" in js_code


def test_generate_components_js_empty_input():
    """Test generate_components_js with empty input."""
    js_code = generate_components_js({})

    assert "export const EMBEDDED_COMPONENTS" in js_code
    assert "0 components from 0 categories" in js_code
