# pip install autora-synthetic==2.2.0 autora-core==5.0.3 autora-theorist-bsr==1.0.0

"""
AutoRA Workflow

Generated by AutoRA Workflow Editor
Generated on: 2026-07-06T23:32:19.086Z
"""

from dataclasses import dataclass, field
from typing import Optional, List

from autora.state import on_state, Delta, estimator_on_state, StandardState
from autora.variable import VariableCollection, Variable
from autora.experimentalist.random import pool as random_pooler, sample as random_sampler
from autora.experiment_runner.synthetic.economics.expected_value_theory import expected_value_theory
from autora.theorist.bsr.regressor import BSRRegressor

import pandas as pd
import numpy as np


# Random Pooler
@on_state()
def random_pooler_on_state(variables: VariableCollection) -> Delta:
    return Delta(conditions=random_pooler(variables, num_samples=5, replace=True))

# Random Sampler
@on_state()
def random_sampler_on_state(conditions: pd.DataFrame, num_samples: int = 1) -> Delta:
    return Delta(conditions=random_sampler(conditions=conditions, num_samples=num_samples, replace=False))

# Expected Value Theory (Synthetic, Economics)
@on_state()
def expected_value_theory_synthetic_economics_on_state(conditions: pd.DataFrame) -> Delta:
    runner = expected_value_theory(choice_temperature=0.1, value_lambda=0.5, resolution=10, minimum_value=-1, maximum_value=1)
    assert runner.run is not None
    return Delta(experiment_data=runner.run(conditions=conditions, added_noise=0.01))

# BSR Regressor
bsr_regressor_on_state = estimator_on_state(BSRRegressor(tree_num=3, itr_num=5000, alpha1=0.4, alpha2=0.4, beta=-1, show_log=False, val=100, last_idx=-1, prior_name="Uniform"))


def main():
    # Variables are created and governed by the experiment runner
    runner = expected_value_theory(choice_temperature=0.1, value_lambda=0.5, resolution=10, minimum_value=-1, maximum_value=1)
    assert runner.variables is not None
    variables = runner.variables
    
    # Initialize state
    state = StandardState(variables=variables)
    
    # Main experiment loop (10 cycles)
    for i in range(10):
        print(f'Cycle {i}')
        
        # Random Pooler
        state = random_pooler_on_state(state)
        
        # Random Sampler
        state = random_sampler_on_state(state, num_samples=1)
        
        # Expected Value Theory (Synthetic, Economics)
        state = expected_value_theory_synthetic_economics_on_state(state)
        
        # BSR Regressor
        state = bsr_regressor_on_state(state)
        
    
    print("Workflow completed!")
    return state


if __name__ == '__main__':
    main()
